version: "3"

services:
  app:
    build: .
    command: npm start
    ports:
      - "3002:3002"
    volumes:
      - .:/usr/app
    environment:
      PORT: ${PORT}
      EMAIL: ${EMAIL}
      PASSWORD: ${PASSWORD}
      DATABASE_URL: ${DATABASE_URL}
